services:
    pubSubModel:
        class: Opine\PubSub\Model
        arguments:
            - %root%
            - "@bundleModel"
    topic:
        class: Opine\PubSub\Topic
        arguments:
            - "@route"
            - "@pubSubModel"
