imports:
    - package-container.yml
    - ../../vendor/opine/container/config/containers/package-container.yml
    - ../../vendor/opine/bundle/config/containers/package-container.yml
    - ../../vendor/opine/route/config/containers/package-container.yml

services:
    pubsubTest:
        class: Test\SomeClass
